"""Ask AGRO-AI memory and artifact routes."""
from __future__ import annotations

import io
import re
from datetime import datetime
from html import escape
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from app.api.deps import get_current_user
from app.core.security import require_current_tenant_id
from app.db.base import get_db
from app.models.saas import Conversation, ConversationMessage, User

router = APIRouter(prefix="/intelligence/chat", tags=["intelligence"])


class PersistMessageRequest(BaseModel):
    content: str = Field(min_length=1, max_length=12000)
    output: str | None = Field(default=None, max_length=50000)


class ReportPdfRequest(BaseModel):
    title: str | None = None
    question: str = "AGRO-AI report"
    answer: str = ""
    uploaded_evidence: list[dict[str, Any]] = Field(default_factory=list)


def _conversation_for(db: Session, tenant_id: str, conversation_id: str) -> Conversation:
    row = db.get(Conversation, conversation_id)
    if not row or row.organization_id != tenant_id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Conversation not found")
    return row


@router.post("/conversations/{conversation_id}/messages")
def persist_message(
    conversation_id: str,
    payload: PersistMessageRequest,
    tenant_id: str = Depends(require_current_tenant_id),
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> dict[str, Any]:
    conversation = _conversation_for(db, tenant_id, conversation_id)
    user_message = ConversationMessage(
        conversation_id=conversation.id,
        organization_id=tenant_id,
        user_id=user.id,
        role="user",
        content=payload.content,
    )
    db.add(user_message)
    if payload.output:
        assistant_message = ConversationMessage(
            conversation_id=conversation.id,
            organization_id=tenant_id,
            user_id=None,
            role="assistant",
            content=payload.output,
            artifacts_json=[],
            citations_json=[],
            missing_data_json=[],
            recommended_actions_json=[],
        )
        db.add(assistant_message)
    conversation.updated_at = datetime.utcnow()
    db.commit()
    return {"ok": True, "conversation_id": conversation.id}


def _plain(value: Any, limit: int = 800) -> str:
    return str(value or "").replace("\n", " ").strip()[:limit]


def _pdf_filename(title: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-") or "agroai-operating-report"
    return f"{slug[:80]}.pdf"


def _safe_paragraph(value: Any) -> str:
    return escape(str(value or "")).replace("\n", "<br/>")


def _rows_count(item: dict[str, Any]) -> int:
    value = item.get("rows_parsed")
    if value is None:
        value = item.get("rows")
    try:
        return max(0, int(float(value)))
    except (TypeError, ValueError):
        return 0


def _upload_line(item: dict[str, Any]) -> str:
    filename = _plain(item.get("filename") or item.get("name"), 160)
    file_type = _plain(item.get("file_type") or item.get("source_type") or item.get("content_type"), 80)
    rows = item.get("rows_parsed") or item.get("rows")
    columns = item.get("columns") or []
    bits = [filename, file_type]
    if rows is not None:
        bits.append(f"rows={rows}")
    if columns:
        bits.append("columns=" + ", ".join(str(col) for col in columns[:12]))
    return " - ".join(bit for bit in bits if bit)


@router.post("/report-pdf")
def report_pdf(
    payload: ReportPdfRequest,
    tenant_id: str = Depends(require_current_tenant_id),
    _user: User = Depends(get_current_user),
) -> StreamingResponse:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    title = payload.title or "AGRO-AI Operating Report"
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        title=title,
        rightMargin=42,
        leftMargin=42,
        topMargin=42,
        bottomMargin=42,
    )
    styles = getSampleStyleSheet()
    story: list[Any] = [
        Paragraph(_safe_paragraph(title), styles["Title"]),
        Spacer(1, 10),
        Paragraph("Generated by AGRO-AI Report Factory v1", styles["Normal"]),
        Paragraph(f"Generated: {datetime.utcnow().isoformat(timespec='seconds')}Z", styles["Normal"]),
        Paragraph(f"Workspace: {escape(tenant_id)}", styles["Normal"]),
        Spacer(1, 14),
        Paragraph("Request", styles["Heading2"]),
        Paragraph(_safe_paragraph(_plain(payload.question, 2200)), styles["BodyText"]),
        Spacer(1, 12),
        Paragraph("AGRO-AI analysis", styles["Heading2"]),
    ]

    blocks = [block.strip() for block in (payload.answer or "").split("\n\n") if block.strip()]
    for block in blocks or ["No report body was provided."]:
        story.append(Paragraph(_safe_paragraph(block), styles["BodyText"]))
        story.append(Spacer(1, 8))

    story.append(Spacer(1, 10))
    story.append(Paragraph("Imported files and parsed evidence", styles["Heading2"]))
    if payload.uploaded_evidence:
        table_data = [["File", "Type", "Rows", "Columns / notes"]]
        for item in payload.uploaded_evidence[:12]:
            columns = item.get("columns") or []
            warnings = item.get("warnings") or []
            details = ", ".join(str(column) for column in columns[:8])
            if warnings:
                details = (details + " | " if details else "") + "; ".join(str(warning) for warning in warnings[:2])
            table_data.append([
                _plain(item.get("filename") or item.get("name"), 34),
                _plain(item.get("file_type") or item.get("source_type") or item.get("content_type"), 22),
                str(_rows_count(item)) if item.get("rows_parsed") is not None or item.get("rows") is not None else "—",
                _plain(details or "—", 70),
            ])
        table = Table(table_data, colWidths=[150, 90, 45, 230], repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0D2B1E")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#D7DFD8")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(table)
        story.append(Spacer(1, 10))
        for item in payload.uploaded_evidence[:10]:
            story.append(Paragraph(_safe_paragraph(_upload_line(item)), styles["BodyText"]))
            story.append(Spacer(1, 4))
    else:
        story.append(Paragraph("No imported files were attached to this report request.", styles["BodyText"]))

    story.append(Spacer(1, 14))
    story.append(Paragraph("Decision-use note", styles["Heading2"]))
    story.append(Paragraph(
        "This is a generated operating draft. A reviewer should confirm source files, field mapping, timestamps, and telemetry claims before external use.",
        styles["BodyText"],
    ))

    doc.build(story)
    buffer.seek(0)
    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{_pdf_filename(title)}"'},
    )
