from datetime import date, timedelta
from typing import List, Dict, Optional

from fastapi import APIRouter
from pydantic import BaseModel

router = APIRouter()


class DemoRequest(BaseModel):
    field_id: str
    crop: str
    acres: float
    location: str
    soil_type: Optional[str] = None
    baseline_inches_per_week: Optional[float] = 1.5


class DemoRecommendation(BaseModel):
    field_id: str
    crop: str
    acres: float
    location: str
    season: str
    total_inches: float
    estimated_savings_pct: float
    baseline_inches_per_week: float
    schedule: List[Dict[str, float]]
    notes: Optional[str] = None


@router.post("/recommendation", response_model=DemoRecommendation)
async def get_demo_recommendation(payload: DemoRequest) -> DemoRecommendation:
    """
    Stub endpoint: returns a deterministic demo schedule + ~27% savings.
    This is for demos/docs only – not production agronomy yet.
    """
    weeks = 4
    days = weeks * 7
    baseline_daily = (payload.baseline_inches_per_week or 1.5) / 7.0

    # 27% water savings vs baseline
    target_daily = baseline_daily * (1 - 0.27)

    today = date.today()
    schedule = []
    for i in range(days):
        d = today + timedelta(days=i)
        schedule.append({"date": d.isoformat(), "inches": round(target_daily, 3)})

    total_inches = round(target_daily * days, 2)

    return DemoRecommendation(
        field_id=payload.field_id,
        crop=payload.crop,
        acres=payload.acres,
        location=payload.location,
        season=f"{today.year}-demo",
        total_inches=total_inches,
        estimated_savings_pct=27.0,
        baseline_inches_per_week=round(payload.baseline_inches_per_week or 1.5, 2),
        schedule=schedule,
        notes="Demo-only schedule generated by AGRO-AI demo endpoint.",
    )
