export const PLATFORM_INTELLIGENCE_COPY = {
  brand: "AGRO-AI",
  product: "Intelligence API",
  navOverview: "Overview",
  navKeys: "API Keys",
  navPlayground: "Playground",
  navUsage: "Usage",
  navBilling: "Usage & Billing",
  navDocs: "Docs",
  navAdvanced: "Advanced",
  headerTagline: "Agricultural intelligence, one API.",
  liveBadge: "Advisory LIVE",
  addFunds: "Add funds",
  balance: "Balance",
  overviewEyebrow: "AGRO-AI Intelligence API",
  overviewTitle: "Put agricultural intelligence inside your product.",
  overviewBody: "Fund your balance, create one restricted LIVE advisory key, and send agricultural context to one endpoint. AGRO-AI handles agricultural reasoning, evidence, model routing and safe fallbacks behind the API.",
  runIntelligence: "Run intelligence",
  prepaidDetail: "Prepaid. No surprise invoice.",
  apiLabel: "API",
  apiLive: "LIVE",
  advisoryDetail: "Advisory intelligence is self-serve.",
  startingAt: "Starting at",
  completedRunDetail: "Per completed intelligence run.",
  startMinutes: "Start in minutes",
  step1Title: "Add funds",
  step1Body: "Prepay $10 or more.",
  step2Title: "Create key",
  step2Body: "Get an agro_live_ advisory key.",
  step3Title: "Call intelligence",
  step3Body: "POST agricultural context to /v1/intelligence.",
  addTen: "Add $10",
  createKey: "Create API key",
  whatBuying: "What you are buying",
  whatBuyingBody: "Evidence-grounded agricultural answers, diagnoses, irrigation plans, risk analysis, decisions and reports—not generic model tokens.",
  physicalBoundary: "Self-serve keys cannot execute physical actions. Machine, valve, chemical and provider-write actions remain separately controlled.",
  credentialsEyebrow: "Credentials",
  credentialsTitle: "One key. One intelligence endpoint.",
  credentialsBody: "This LIVE key is intentionally limited to advisory intelligence. It cannot execute physical actions or write to agricultural equipment providers.",
  keyCreated: "Your LIVE API key was created",
  keyCopyOnce: "Copy it now. For security, the full secret is shown only once.",
  productionIntelligence: "Production intelligence",
  scopeLabel: "Scope: intelligence:run",
  createNewKey: "Create new key",
  endpoint: "Endpoint",
  authHint: "Use Authorization: Bearer $AGROAI_API_KEY or X-API-Key. Every request also requires an Idempotency-Key.",
  playgroundEyebrow: "Playground",
  playgroundTitle: "Test real agricultural intelligence.",
  playgroundBody: "The Playground uses the same paid intelligence engine as your API key. Only successfully completed runs are charged.",
  taskLabel: "Intelligence task",
  questionLabel: "Question",
  inputLabel: "Agricultural input JSON",
  successfulCost: "Cost on successful completion",
  response: "Response",
  responseEmptyTitle: "Your intelligence result appears here.",
  responseEmptyBody: "Structured decision, evidence, confidence, risk flags, missing data and the exact charge.",
  insufficientBalance: "Your intelligence balance is too low for this run. Add funds and retry.",
  usageEyebrow: "Usage",
  usageTitle: "Every dollar maps to intelligence.",
  usageBody: "Usage is shown in money, not abstract tokens. Each completed intelligence task has a published price.",
  currentBalance: "Current balance",
  lifetimeFunded: "Lifetime funded",
  lifetimeSpend: "Lifetime intelligence spend",
  pricingTitle: "Intelligence pricing",
  billingEyebrow: "Usage & Billing",
  billingTitle: "Prepay. Call intelligence. Stay in control.",
  billingBody: "Add funds securely with Stripe. Your wallet is credited only after AGRO-AI verifies the paid session, purchased subtotal, currency and organization metadata.",
  availableBalance: "Available balance",
  minimumTopup: "Minimum top-up",
  recentActivity: "Recent activity",
  noActivity: "No intelligence wallet activity yet.",
  docsEyebrow: "Documentation",
  docsTitle: "One endpoint for agricultural intelligence.",
  docsBody: "Send agricultural context and a task. Receive a structured agricultural intelligence object.",
  authentication: "Authentication",
  model: "Model",
  curl: "cURL",
  python: "Python",
  productionContract: "Production contract",
  contractIdempotency: "Every request requires an idempotency key. Safe retries return the same completed result instead of charging twice.",
  contractBilling: "Failed or degraded runs are not charged.",
  contractStateful: "Stateful calls can reference AGRO-AI field/workspace IDs; stateless calls can carry context directly.",
  contractSafety: "Self-serve keys are advisory only. Physical execution requires separate authorization.",
  loading: "Loading…",
  copy: "Copy",
  copied: "Copied",
  live: "LIVE",
  defaultQuestion: "What requires attention in this field today?",
  loadError: "The AGRO-AI Platform could not load.",
  checkoutError: "Checkout could not start.",
  checkoutUrlError: "Secure checkout did not return a valid URL.",
  keyError: "API key could not be created.",
  runError: "The intelligence run failed.",
} as const;
