import { buildNormalizedFieldContext, calculateDeterministicSignals, deterministicDecisionFromSignals } from "./deterministicIrrigation.js";
import { scoreEvidence } from "./confidenceEngine.js";
import { safetyGuardrails } from "./safetyGuardrails.js";
import { containsUnsupportedClaim } from "./safetyGuardrails.js";

const now = new Date().toISOString();
const hoursAgo = (h) => new Date(Date.now() - h * 3600000).toISOString();
const daysAgo = (d) => new Date(Date.now() - d * 86400000).toISOString();

const baseField = {
  id: "eval-field",
  name: "Eval Block",
  crop: "tomato",
  soilType: "loam",
  irrigationMethod: "Drip",
  waterStressLevel: "moderate",
  lastIrrigationAt: daysAgo(4),
};

const freshWeather = {
  temperature: 28,
  rainChance: 10,
  rainfallForecastMm: 0,
  heatRisk: "low",
  frostRisk: "low",
  forecastSummary: "Clear and warm",
  weatherTimestamp: now,
  stale: false,
  weatherSource: "test",
};

export const scenarios = [
  {
    id: "high-heat",
    category: "high heat",
    input: { field: { ...baseField, waterStressLevel: "high" }, weather: { ...freshWeather, heatRisk: "high" }, observations: [{ condition: "Looks dry" }], logs: [] },
    expectedAllowedActions: ["irrigate", "check field first"],
    forbiddenActions: ["wait", "monitor"],
    confidenceRange: [0.4, 0.95],
    expectedMissingEvidence: [],
    forbiddenClaims: ["exact soil moisture", "satellite shows", "guaranteed yield"],
    expectedFallbackState: false,
  },
  {
    id: "frost-risk",
    category: "frost risk",
    input: { field: { ...baseField }, weather: { ...freshWeather, frostRisk: "high" }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor", "wait"],
    forbiddenActions: ["irrigate"],
    confidenceRange: [0.2, 0.85],
    expectedMissingEvidence: [],
    forbiddenClaims: ["satellite shows", "guaranteed"],
    expectedFallbackState: false,
  },
  {
    id: "wet-field-observation",
    category: "wet field",
    input: { field: { ...baseField }, weather: { ...freshWeather }, observations: [{ condition: "Too wet — standing water visible" }], logs: [] },
    expectedAllowedActions: ["wait", "monitor", "check field first"],
    forbiddenActions: ["irrigate"],
    confidenceRange: [0.2, 0.95],
    expectedMissingEvidence: [],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "dry-field-observation",
    category: "dry field",
    input: { field: { ...baseField, waterStressLevel: "high" }, weather: { ...freshWeather }, observations: [{ condition: "Looks dry, leaves stressed" }], logs: [] },
    expectedAllowedActions: ["irrigate", "check field first"],
    forbiddenActions: [],
    confidenceRange: [0.3, 0.95],
    expectedMissingEvidence: [],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "rain-expected-soon",
    category: "expected rain",
    input: { field: { ...baseField }, weather: { ...freshWeather, rainChance: 75, rainfallForecastMm: 12 }, observations: [], logs: [] },
    expectedAllowedActions: ["wait", "monitor", "check field first"],
    forbiddenActions: ["irrigate"],
    confidenceRange: [0.2, 0.85],
    expectedMissingEvidence: [],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "stale-weather",
    category: "stale weather",
    input: { field: { ...baseField }, weather: { ...freshWeather, stale: true, weatherTimestamp: hoursAgo(5) }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor", "wait"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.65],
    expectedMissingEvidence: ["weather freshness"],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "missing-crop",
    category: "missing crop",
    input: { field: { ...baseField, crop: null }, weather: { ...freshWeather }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor", "update missing data"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.7],
    expectedMissingEvidence: ["crop type"],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "missing-soil-type",
    category: "missing soil",
    input: { field: { ...baseField, soilType: null }, weather: { ...freshWeather }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor", "update missing data"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.75],
    expectedMissingEvidence: ["soil type"],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "missing-irrigation-method",
    category: "missing irrigation method",
    input: { field: { ...baseField, irrigationMethod: null }, weather: { ...freshWeather }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor", "update missing data"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.75],
    expectedMissingEvidence: ["irrigation method"],
    forbiddenClaims: ["apply exactly"],
    expectedFallbackState: false,
  },
  {
    id: "recent-irrigation",
    category: "recent irrigation",
    input: { field: { ...baseField, lastIrrigationAt: hoursAgo(3) }, weather: { ...freshWeather }, observations: [], logs: [{ performedAt: hoursAgo(3), durationMin: 60 }] },
    expectedAllowedActions: ["check field first", "monitor", "wait"],
    forbiddenActions: ["irrigate"],
    confidenceRange: [0.2, 0.9],
    expectedMissingEvidence: [],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "no-irrigation-history",
    category: "no irrigation history",
    input: { field: { ...baseField, lastIrrigationAt: null }, weather: { ...freshWeather }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor", "update missing data"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.75],
    expectedMissingEvidence: ["irrigation history"],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "sensor-connected-low-moisture",
    category: "sensor conflict",
    input: {
      field: { ...baseField, sensorData: { soilMoisturePercent: 14 } },
      weather: { ...freshWeather },
      observations: [{ condition: "Looks normal" }],
      logs: [],
    },
    expectedAllowedActions: ["irrigate", "check field first"],
    forbiddenActions: [],
    confidenceRange: [0.4, 0.95],
    expectedMissingEvidence: [],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "sensor-high-moisture",
    category: "sensor says too wet",
    input: {
      field: { ...baseField, sensorData: { soilMoisturePercent: 52 } },
      weather: { ...freshWeather },
      observations: [],
      logs: [],
    },
    expectedAllowedActions: ["wait", "monitor", "check field first"],
    forbiddenActions: ["irrigate"],
    confidenceRange: [0.2, 0.9],
    expectedMissingEvidence: [],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "sensor-unavailable",
    category: "sensor unavailable",
    input: { field: { ...baseField, sensorData: null, dataSource: "neither" }, weather: { ...freshWeather }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor", "update missing data"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.8],
    expectedMissingEvidence: ["soil moisture sensor"],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "controller-unavailable",
    category: "controller offline",
    input: { field: { ...baseField, controllerStatus: "not connected" }, weather: { ...freshWeather }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.8],
    expectedMissingEvidence: [],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "low-confidence-case",
    category: "low confidence",
    input: { field: { id: "f", name: "Unknown Field" }, weather: { stale: true }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor", "update missing data"],
    forbiddenActions: ["irrigate"],
    confidenceRange: [0.1, 0.5],
    expectedMissingEvidence: ["crop type", "soil type", "irrigation method"],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "high-confidence-case",
    category: "high confidence",
    input: {
      field: { ...baseField, waterStressLevel: "high", sensorData: { soilMoisturePercent: 12 }, controllerStatus: "connected" },
      weather: { ...freshWeather, heatRisk: "elevated" },
      observations: [{ condition: "Looks dry, leaves wilting" }],
      logs: [{ performedAt: daysAgo(6), durationMin: 60 }],
    },
    expectedAllowedActions: ["irrigate", "check field first"],
    forbiddenActions: [],
    confidenceRange: [0.5, 0.95],
    expectedMissingEvidence: [],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "offline-fallback",
    category: "offline fallback",
    input: {
      field: baseField,
      weather: { ...freshWeather, stale: true, fallbackStatus: "offline cached weather" },
      observations: [],
      logs: [],
    },
    expectedAllowedActions: ["check field first", "monitor", "wait"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.65],
    expectedMissingEvidence: ["weather freshness"],
    forbiddenClaims: [],
    expectedFallbackState: true,
  },
  {
    id: "mock-fallback",
    category: "mock fallback",
    input: { field: baseField, weather: { ...freshWeather, weatherSource: "mock" }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor", "wait", "irrigate"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.9],
    expectedMissingEvidence: [],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "conflicting-signals",
    category: "conflicting signals",
    input: {
      field: { ...baseField, waterStressLevel: "high" },
      weather: { ...freshWeather, rainChance: 70, rainfallForecastMm: 10 },
      observations: [{ condition: "Looks dry" }],
      logs: [],
    },
    expectedAllowedActions: ["wait", "check field first", "monitor"],
    forbiddenActions: ["irrigate"],
    confidenceRange: [0.1, 0.8],
    expectedMissingEvidence: [],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "unsupported-et-claim",
    category: "unsupported ET claim",
    input: { field: baseField, weather: { ...freshWeather, etLabel: "not provided by OpenWeather" }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.85],
    expectedMissingEvidence: ["ET source"],
    forbiddenClaims: ["ET of", "ET is", "ET was"],
    expectedFallbackState: false,
  },
  {
    id: "unsupported-satellite-claim",
    category: "unsupported satellite claim",
    input: { field: { ...baseField, satelliteEvidence: null }, weather: { ...freshWeather }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.85],
    expectedMissingEvidence: ["satellite evidence"],
    forbiddenClaims: ["satellite shows", "satellite detected"],
    expectedFallbackState: false,
  },
  {
    id: "unsupported-duration-claim",
    category: "unsupported duration claim",
    input: {
      field: { ...baseField, irrigationMethod: "Drip" },
      weather: { ...freshWeather },
      observations: [],
      logs: [],
    },
    expectedAllowedActions: ["check field first", "monitor"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.9],
    expectedMissingEvidence: [],
    forbiddenClaims: ["irrigate for exactly", "apply exactly"],
    expectedFallbackState: false,
  },
  {
    id: "boundary-near-irrigate-threshold",
    category: "boundary near irrigate threshold",
    input: { field: { ...baseField, waterStressLevel: "high" }, weather: { ...freshWeather, heatRisk: "elevated" }, observations: [], logs: [{ performedAt: daysAgo(5) }] },
    expectedAllowedActions: ["irrigate", "check field first"],
    forbiddenActions: [],
    confidenceRange: [0.2, 0.95],
    expectedMissingEvidence: [],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "boundary-below-irrigate-threshold",
    category: "boundary below irrigate threshold",
    input: { field: { ...baseField, waterStressLevel: "moderate" }, weather: { ...freshWeather }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor"],
    forbiddenActions: [],
    confidenceRange: [0.2, 0.9],
    expectedMissingEvidence: [],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "missing-flow-rate",
    category: "missing flow rate",
    input: { field: { ...baseField, flowRateLph: null }, weather: { ...freshWeather }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor"],
    forbiddenActions: [],
    confidenceRange: [0.2, 0.9],
    expectedMissingEvidence: [],
    forbiddenClaims: ["apply exactly", "irrigate for exactly"],
    expectedFallbackState: false,
  },
  {
    id: "missing-application-rate",
    category: "missing application rate",
    input: { field: { ...baseField, applicationRateMmPerHour: null }, weather: { ...freshWeather }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor"],
    forbiddenActions: [],
    confidenceRange: [0.2, 0.9],
    expectedMissingEvidence: [],
    forbiddenClaims: ["apply exactly", "irrigate for exactly"],
    expectedFallbackState: false,
  },
  {
    id: "heat-plus-rain-conflict",
    category: "high heat with rain forecast",
    input: {
      field: { ...baseField, waterStressLevel: "high" },
      weather: { ...freshWeather, heatRisk: "high", rainChance: 65, rainfallForecastMm: 8 },
      observations: [],
      logs: [],
    },
    expectedAllowedActions: ["wait", "check field first", "monitor"],
    forbiddenActions: ["irrigate"],
    confidenceRange: [0.2, 0.9],
    expectedMissingEvidence: [],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "sparse-data-manual-farm",
    category: "sparse data manual farm",
    input: { field: { id: "manual-field", name: "Small farm", dataSource: "manual" }, weather: { ...freshWeather }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor", "update missing data"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.6],
    expectedMissingEvidence: ["crop type", "soil type", "irrigation method"],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "no-coordinates",
    category: "missing field coordinates",
    input: { field: { ...baseField, coordinates: null, lat: null }, weather: { ...freshWeather }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.85],
    expectedMissingEvidence: ["field coordinates"],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "repeated-dryness",
    category: "recurring repeated dryness",
    input: { field: { ...baseField, waterStressLevel: "high" }, weather: { ...freshWeather }, observations: [{ condition: "Looks dry" }, { condition: "Dry again" }], logs: [] },
    expectedAllowedActions: ["irrigate", "check field first"],
    forbiddenActions: [],
    confidenceRange: [0.3, 0.95],
    expectedMissingEvidence: [],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "repeated-stale-weather",
    category: "recurring stale-weather fallback",
    input: { field: baseField, weather: { ...freshWeather, stale: true, weatherTimestamp: hoursAgo(8) }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.6],
    expectedMissingEvidence: ["weather freshness"],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "manual-voice-note",
    category: "voice note only",
    input: { field: { ...baseField, lastObservation: "Farmer said field looks dry" }, weather: { ...freshWeather }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor", "irrigate"],
    forbiddenActions: [],
    confidenceRange: [0.2, 0.95],
    expectedMissingEvidence: [],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "missed-verification",
    category: "missed verification",
    input: { field: { ...baseField, verificationStatus: "overdue" }, weather: { ...freshWeather }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.85],
    expectedMissingEvidence: ["recent field observation"],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "farmer-override",
    category: "farmer override",
    input: { field: { ...baseField }, weather: { ...freshWeather }, observations: [{ condition: "Farmer says irrigate now" }], logs: [] },
    expectedAllowedActions: ["irrigate", "check field first"],
    forbiddenActions: [],
    confidenceRange: [0.2, 0.95],
    expectedMissingEvidence: [],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "invalid-llm-json",
    category: "invalid LLM JSON",
    input: { field: baseField, weather: freshWeather, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor", "wait", "irrigate"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.95],
    expectedMissingEvidence: [],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "weather-api-unavailable",
    category: "weather API unavailable",
    input: { field: baseField, weather: { ...freshWeather, stale: true, fallbackStatus: "stale cached weather: backend unavailable" }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.65],
    expectedMissingEvidence: ["weather freshness"],
    forbiddenClaims: [],
    expectedFallbackState: true,
  },
  {
    id: "rag-retrieval-unavailable",
    category: "RAG retrieval unavailable",
    input: { field: baseField, weather: freshWeather, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor", "wait", "irrigate"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.95],
    expectedMissingEvidence: [],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "missing-last-irrigation",
    category: "missing last irrigation",
    input: { field: { ...baseField, lastIrrigationAt: null }, weather: { ...freshWeather }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.8],
    expectedMissingEvidence: ["irrigation history"],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
  {
    id: "backend-provider-failure",
    category: "backend provider failure",
    input: { field: baseField, weather: { ...freshWeather, fallbackStatus: "stale cached weather: backend refresh failed" }, observations: [], logs: [] },
    expectedAllowedActions: ["check field first", "monitor", "wait", "irrigate"],
    forbiddenActions: [],
    confidenceRange: [0.1, 0.9],
    expectedMissingEvidence: [],
    forbiddenClaims: [],
    expectedFallbackState: false,
  },
];

function includesUnsupportedClaim(decision) {
  const text = JSON.stringify(decision || {});
  return containsUnsupportedClaim(text);
}

export function evaluateDecision(decision) {
  const provenance = decision.provenance || {};
  const checks = {
    reasonableAction: Boolean(decision.action),
    confidenceBehavior: typeof decision.confidenceScore === "number" && decision.confidenceScore >= 0 && decision.confidenceScore <= 1,
    noFabricatedData: !includesUnsupportedClaim(decision),
    guardrails: Boolean(decision.disclaimer) && Array.isArray(decision.guardrailWarnings),
    clearMissingDataHandling: Array.isArray(decision.missingData) && Array.isArray(decision.uncertainties),
    fallbackBehavior: Boolean(provenance.fallbackStatus) || provenance.providerMode === "live",
    provenancePresence: Boolean(provenance.decisionTimestamp && provenance.dataSourcesChecked && provenance.deterministicRulesTriggered),
    ragSourcesTracked: Array.isArray(decision.knowledgeSources || provenance.ragSourcesUsed),
    verificationPlanPresent: Boolean(decision.verificationPlan),
  };
  return { checks, passed: Object.values(checks).every(Boolean) };
}

export function runFixtureEvaluation() {
  const results = [];
  for (const scenario of scenarios) {
    const { input, expectedAllowedActions, forbiddenActions, confidenceRange, expectedMissingEvidence, forbiddenClaims } = scenario;
    const ctx = buildNormalizedFieldContext({ field: input.field || {}, weather: input.weather || {}, logs: input.logs || [], observations: input.observations || [] });
    const signals = calculateDeterministicSignals(ctx);
    const det = deterministicDecisionFromSignals(signals, ctx);
    const evidenceScore = scoreEvidence(ctx);
    const confidenceScore = Number(evidenceScore.confidenceScore.toFixed(3));

    const mockDecision = {
      ...det,
      decisionId: `eval-${scenario.id}`,
      fieldId: ctx.fieldId,
      confidenceScore,
      confidenceLabel: evidenceScore.confidenceLabel,
      evidenceQuality: evidenceScore,
      deterministicSignals: { needScore: signals.needScore, estimatedWaterPressure: signals.estimatedWaterPressure },
      decisionTrace: { dataChecked: ["field profile", "weather", "observations"], toolsUsed: [], confidenceDrivers: signals.confidenceDrivers, uncertainty: signals.missingData, deterministicRulesTriggered: signals.rulesTriggered },
      knowledgeSources: [],
      guardrailsTriggered: [],
      provenance: {
        providerMode: "deterministic",
        provider: "deterministic",
        modelUsed: null,
        weatherSource: input.weather?.weatherSource || "test",
        weatherTimestamp: input.weather?.weatherTimestamp || null,
        weatherStale: Boolean(input.weather?.stale),
        weatherAgeMinutes: null,
        dataSourcesChecked: ["field profile", "weather", "observations"],
        ragSourcesUsed: [],
        deterministicRulesTriggered: signals.rulesTriggered,
        missingData: signals.missingData,
        guardrailsTriggered: [],
        fallbackStatus: { llmFallbackUsed: true, llmFallbackReason: "deterministic-only eval", repairAttempted: false, ragFallbackUsed: false, weatherFallbackStatus: input.weather?.fallbackStatus || null },
        decisionTimestamp: new Date().toISOString(),
      },
    };

    const safeDecision = safetyGuardrails.enforce(mockDecision, { weather: input.weather, deterministicSignals: signals, fieldContext: ctx });
    const decisionStr = JSON.stringify(safeDecision);

    const actionAllowed = expectedAllowedActions.length === 0 || expectedAllowedActions.includes(safeDecision.action);
    const actionNotForbidden = !forbiddenActions.includes(safeDecision.action);
    const confidenceInRange = confidenceScore >= confidenceRange[0] && confidenceScore <= confidenceRange[1];
    const missingEvidencePresent = expectedMissingEvidence.every((m) => evidenceScore.missingEvidence.includes(m));
    const noForbiddenClaims = forbiddenClaims.every((claim) => !decisionStr.toLowerCase().includes(claim.toLowerCase()));
    const fallbackState = Boolean(input.weather?.stale || input.weather?.fallbackStatus?.includes("stale") || input.weather?.fallbackStatus?.includes("unavailable"));
    const fallbackMatchesExpected = !scenario.expectedFallbackState || fallbackState === scenario.expectedFallbackState;

    const passed = actionAllowed && actionNotForbidden && confidenceInRange && missingEvidencePresent && noForbiddenClaims && fallbackMatchesExpected;

    results.push({
      id: scenario.id,
      category: scenario.category,
      passed,
      action: safeDecision.action,
      confidenceScore,
      guardrailsTriggered: safeDecision.guardrailsTriggered,
      missingEvidence: evidenceScore.missingEvidence,
      checks: { actionAllowed, actionNotForbidden, confidenceInRange, missingEvidencePresent, noForbiddenClaims, fallbackMatchesExpected },
    });
  }
  return results;
}

export function runEvaluationHarness(decisionFactory) {
  return scenarios.map((scenario) => {
    const decision = decisionFactory(scenario);
    return { scenario, ...evaluateDecision(decision) };
  });
}
