name: Infra Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - "terraform/**"
      - ".github/workflows/infra-deploy.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    env:
      TF_IN_AUTOMATION: "true"

      # Prefer repo Variables for non-sensitive IDs
      TF_VAR_project: ${{ vars.PROJECT }}
      TF_VAR_vpc_id: ${{ vars.VPC_ID }}

      # These MUST be valid HCL/JSON list strings in GitHub Variables:
      # Example value: ["subnet-aaa","subnet-bbb"]
      TF_VAR_public_subnet_ids: ${{ vars.PUBLIC_SUBNET_IDS }}
      TF_VAR_ecs_subnet_ids: ${{ vars.ECS_SUBNET_IDS }}

      # Sensitive
      TF_VAR_openweather_api_key: ${{ secrets.OPENWEATHER_API_KEY }}

      # Safe default; you can override
      TF_VAR_image_tag: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::292039821285:role/infra_deploy_role
          aws-region: us-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false
